### ISSUE TITLE
hidden links

### ISSUE THREAD

**Issue by hellaluia** [GavickPro/Magazine-Free-WordPress-Theme#3]
I've downloaded the " Magazine " free wordpress theme and it seems there are some hidden links, or ads, in the header banner, and adblock won't let me see that widget area at all. Is there any way to fix this? I'm confrunting that issue since i've updated the theme, I think. I added a printscreen of what google developer tools finds
![magazine links](https://cloud.githubusercontent.com/assets/10811956/6002311/ea549568-aafa-11e4-90d3-6ec60cb4e377.png)

Thank you!

**Comment by dziudek** [comment]
Solution: disable the adblock for your development page ;)

**Comment by hellaluia** [comment]
Seems legit! 😄 but what about those who also have adblock active, they won't be able to see that widget, whatever i decide to use in that area...a menu or something. What about google...is there any chance to get blocked?
Thanks for reply!

**Comment by dziudek** [comment]
It is a banner area so if somebody wants to use adblock then it don't want to see the banners. I don't see any correlation between google and being blocked for using banner area.

**Comment by hellaluia** [comment]
That's not my problem. Magazine theme has a widget area which is named "Banner Top" and even if i don't add anything to that widget adblock stil blockes it (even if widget area is empty). I don't want to add a banner there, i would like to add a text axactly like the demo page of Magazine wordpress theme  https://www.gavick.com/demo/wordpress/magazine/ (the area next to logo). That is my issue. I havent added any link, links were there in theme's code. As shown in the printscreen above there are many bad links(hidden links), some of them even porn links and that's why i asked about google. Im not sure if those links are in theme's code or not, that is why i'm askin' you.
Thanks for reply and i hope you undestood what i'm trying to say.

**Comment by dziudek** [comment]
If it is so important issue for you, you can always rename the container and all CSS codes connected with it - to remove the "banner" word from the CSS selectors.

Regarding the "porn" links - the code which you have showed is a CSS code added probably by the Adblock extension, used for hiding advertisements ;)

**Comment by hellaluia** [comment]
If that code is not added in theme's code i have absolutely no problem. Is just that in the demo page of magazine template adblock wont block banner top widget area and that' s why i thought those links are hidden in theme's code. If theme's code is clean, i don't mind at all.
Thank you very much for your interest!
